package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autonomia generated by hbm2java
 */
@Entity
@Table(name="Autonomia"
    ,catalog="sc77la_dev"
)
public class Autonomia  implements java.io.Serializable {


     private Integer idAutonomia;
     private String nombreAutonomia;
     private Set provincias = new HashSet(0);

    public Autonomia() {
    }

	
    public Autonomia(String nombreAutonomia) {
        this.nombreAutonomia = nombreAutonomia;
    }
    public Autonomia(String nombreAutonomia, Set provincias) {
       this.nombreAutonomia = nombreAutonomia;
       this.provincias = provincias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_autonomia", unique=true, nullable=false)
    public Integer getIdAutonomia() {
        return this.idAutonomia;
    }
    
    public void setIdAutonomia(Integer idAutonomia) {
        this.idAutonomia = idAutonomia;
    }
    
    @Column(name="nombre_autonomia", nullable=false, length=80)
    public String getNombreAutonomia() {
        return this.nombreAutonomia;
    }
    
    public void setNombreAutonomia(String nombreAutonomia) {
        this.nombreAutonomia = nombreAutonomia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="autonomia")
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


