package com.sc77.entities;
// Generated 27/04/2017 05:32:16 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CentroMaster generated by hbm2java
 */
@Entity
@Table(name="CentroMaster"
    ,catalog="sc77la_dev"
)
public class CentroMaster  implements java.io.Serializable {


     private Integer idCentromaster;
     private Localidad localidad;
     private String nombreCentromaster;
     private String urlCentromaster;
     private String dirSubcentro;
     private Set contactos = new HashSet(0);
     private Set subCentros = new HashSet(0);

    public CentroMaster() {
    }

	
    public CentroMaster(String nombreCentromaster, String urlCentromaster) {
        this.nombreCentromaster = nombreCentromaster;
        this.urlCentromaster = urlCentromaster;
    }
    public CentroMaster(Localidad localidad, String nombreCentromaster, String urlCentromaster, String dirSubcentro, Set contactos, Set subCentros) {
       this.localidad = localidad;
       this.nombreCentromaster = nombreCentromaster;
       this.urlCentromaster = urlCentromaster;
       this.dirSubcentro = dirSubcentro;
       this.contactos = contactos;
       this.subCentros = subCentros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_centromaster", unique=true, nullable=false)
    public Integer getIdCentromaster() {
        return this.idCentromaster;
    }
    
    public void setIdCentromaster(Integer idCentromaster) {
        this.idCentromaster = idCentromaster;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_localidad")
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    
    @Column(name="nombre_centromaster", nullable=false, length=100)
    public String getNombreCentromaster() {
        return this.nombreCentromaster;
    }
    
    public void setNombreCentromaster(String nombreCentromaster) {
        this.nombreCentromaster = nombreCentromaster;
    }
    
    @Column(name="url_centromaster", nullable=false, length=50)
    public String getUrlCentromaster() {
        return this.urlCentromaster;
    }
    
    public void setUrlCentromaster(String urlCentromaster) {
        this.urlCentromaster = urlCentromaster;
    }
    
    @Column(name="dir_subcentro", length=150)
    public String getDirSubcentro() {
        return this.dirSubcentro;
    }
    
    public void setDirSubcentro(String dirSubcentro) {
        this.dirSubcentro = dirSubcentro;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="centroMaster")
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="centroMaster")
    public Set getSubCentros() {
        return this.subCentros;
    }
    
    public void setSubCentros(Set subCentros) {
        this.subCentros = subCentros;
    }




}


