package com.sc77.entities;
// Generated 27/04/2017 05:32:16 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name="Examen"
    ,catalog="sc77la_dev"
)
public class Examen  implements java.io.Serializable {


     private Integer idExamen;
     private SubCentro subCentro;
     private Plazo plazo;
     private Programa programa;
     private Modalidad modalidad;
     private Grado grado;
     private Date fechaExamen;
     private String estado;
     private Set ubicacionExamens = new HashSet(0);

    public Examen() {
    }

	
    public Examen(SubCentro subCentro, Plazo plazo, Programa programa, Modalidad modalidad, Grado grado, Date fechaExamen, String estado) {
        this.subCentro = subCentro;
        this.plazo = plazo;
        this.programa = programa;
        this.modalidad = modalidad;
        this.grado = grado;
        this.fechaExamen = fechaExamen;
        this.estado = estado;
    }
    public Examen(SubCentro subCentro, Plazo plazo, Programa programa, Modalidad modalidad, Grado grado, Date fechaExamen, String estado, Set ubicacionExamens) {
       this.subCentro = subCentro;
       this.plazo = plazo;
       this.programa = programa;
       this.modalidad = modalidad;
       this.grado = grado;
       this.fechaExamen = fechaExamen;
       this.estado = estado;
       this.ubicacionExamens = ubicacionExamens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_examen", unique=true, nullable=false)
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_subcentro", nullable=false)
    public SubCentro getSubCentro() {
        return this.subCentro;
    }
    
    public void setSubCentro(SubCentro subCentro) {
        this.subCentro = subCentro;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_plazo", nullable=false)
    public Plazo getPlazo() {
        return this.plazo;
    }
    
    public void setPlazo(Plazo plazo) {
        this.plazo = plazo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_programa", nullable=false)
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_modalidad", nullable=false)
    public Modalidad getModalidad() {
        return this.modalidad;
    }
    
    public void setModalidad(Modalidad modalidad) {
        this.modalidad = modalidad;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_grado", nullable=false)
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_examen", nullable=false, length=10)
    public Date getFechaExamen() {
        return this.fechaExamen;
    }
    
    public void setFechaExamen(Date fechaExamen) {
        this.fechaExamen = fechaExamen;
    }
    
    @Column(name="estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="examen")
    public Set getUbicacionExamens() {
        return this.ubicacionExamens;
    }
    
    public void setUbicacionExamens(Set ubicacionExamens) {
        this.ubicacionExamens = ubicacionExamens;
    }




}


