package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grado generated by hbm2java
 */
@Entity
@Table(name="Grado"
    ,catalog="sc77la_dev"
)
public class Grado  implements java.io.Serializable {


     private Integer idGrado;
     private String descGrado;
     private String categoriaGrado;
     private String nombreCortoGrado;
     private Set examens = new HashSet(0);

    public Grado() {
    }

	
    public Grado(String descGrado, String categoriaGrado, String nombreCortoGrado) {
        this.descGrado = descGrado;
        this.categoriaGrado = categoriaGrado;
        this.nombreCortoGrado = nombreCortoGrado;
    }
    public Grado(String descGrado, String categoriaGrado, String nombreCortoGrado, Set examens) {
       this.descGrado = descGrado;
       this.categoriaGrado = categoriaGrado;
       this.nombreCortoGrado = nombreCortoGrado;
       this.examens = examens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_grado", unique=true, nullable=false)
    public Integer getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(Integer idGrado) {
        this.idGrado = idGrado;
    }
    
    @Column(name="desc_grado", nullable=false, length=70)
    public String getDescGrado() {
        return this.descGrado;
    }
    
    public void setDescGrado(String descGrado) {
        this.descGrado = descGrado;
    }
    
    @Column(name="categoria_grado", nullable=false, length=35)
    public String getCategoriaGrado() {
        return this.categoriaGrado;
    }
    
    public void setCategoriaGrado(String categoriaGrado) {
        this.categoriaGrado = categoriaGrado;
    }
    
    @Column(name="nombre_corto_grado", nullable=false, length=20)
    public String getNombreCortoGrado() {
        return this.nombreCortoGrado;
    }
    
    public void setNombreCortoGrado(String nombreCortoGrado) {
        this.nombreCortoGrado = nombreCortoGrado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="grado")
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


