package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name="Localidad"
    ,catalog="sc77la_dev"
)
public class Localidad  implements java.io.Serializable {


     private Integer idLocalidad;
     private Provincia provincia;
     private String nombreLocalidad;
     private Set centroMasters = new HashSet(0);
     private Set subCentros = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(Provincia provincia, String nombreLocalidad) {
        this.provincia = provincia;
        this.nombreLocalidad = nombreLocalidad;
    }
    public Localidad(Provincia provincia, String nombreLocalidad, Set centroMasters, Set subCentros) {
       this.provincia = provincia;
       this.nombreLocalidad = nombreLocalidad;
       this.centroMasters = centroMasters;
       this.subCentros = subCentros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_localidad", unique=true, nullable=false)
    public Integer getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_provincia", nullable=false)
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    
    @Column(name="nombre_localidad", nullable=false, length=80)
    public String getNombreLocalidad() {
        return this.nombreLocalidad;
    }
    
    public void setNombreLocalidad(String nombreLocalidad) {
        this.nombreLocalidad = nombreLocalidad;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="localidad")
    public Set getCentroMasters() {
        return this.centroMasters;
    }
    
    public void setCentroMasters(Set centroMasters) {
        this.centroMasters = centroMasters;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="localidad")
    public Set getSubCentros() {
        return this.subCentros;
    }
    
    public void setSubCentros(Set subCentros) {
        this.subCentros = subCentros;
    }




}


