package com.sc77.entities;
// Generated 27/04/2017 05:32:16 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modalidad generated by hbm2java
 */
@Entity
@Table(name="Modalidad"
    ,catalog="sc77la_dev"
)
public class Modalidad  implements java.io.Serializable {


     private Integer idModalidad;
     private String descModalidad;
     private Set examens = new HashSet(0);

    public Modalidad() {
    }

	
    public Modalidad(String descModalidad) {
        this.descModalidad = descModalidad;
    }
    public Modalidad(String descModalidad, Set examens) {
       this.descModalidad = descModalidad;
       this.examens = examens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_modalidad", unique=true, nullable=false)
    public Integer getIdModalidad() {
        return this.idModalidad;
    }
    
    public void setIdModalidad(Integer idModalidad) {
        this.idModalidad = idModalidad;
    }
    
    @Column(name="desc_modalidad", nullable=false, length=35)
    public String getDescModalidad() {
        return this.descModalidad;
    }
    
    public void setDescModalidad(String descModalidad) {
        this.descModalidad = descModalidad;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="modalidad")
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


