package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parte generated by hbm2java
 */
@Entity
@Table(name="Parte"
    ,catalog="sc77la_dev"
)
public class Parte  implements java.io.Serializable {


     private Integer idParte;
     private String descParte;
     private Set programas = new HashSet(0);

    public Parte() {
    }

	
    public Parte(String descParte) {
        this.descParte = descParte;
    }
    public Parte(String descParte, Set programas) {
       this.descParte = descParte;
       this.programas = programas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_parte", unique=true, nullable=false)
    public Integer getIdParte() {
        return this.idParte;
    }
    
    public void setIdParte(Integer idParte) {
        this.idParte = idParte;
    }
    
    @Column(name="desc_parte", nullable=false, length=70)
    public String getDescParte() {
        return this.descParte;
    }
    
    public void setDescParte(String descParte) {
        this.descParte = descParte;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="parte")
    public Set getProgramas() {
        return this.programas;
    }
    
    public void setProgramas(Set programas) {
        this.programas = programas;
    }




}


