package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permisos generated by hbm2java
 */
@Entity
@Table(name="Permisos"
    ,catalog="sc77la_dev"
)
public class Permisos  implements java.io.Serializable {


     private Integer idPermiso;
     private Perfil perfil;
     private String nombrePermiso;

    public Permisos() {
    }

    public Permisos(Perfil perfil, String nombrePermiso) {
       this.perfil = perfil;
       this.nombrePermiso = nombrePermiso;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_permiso", unique=true, nullable=false)
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_perfil", nullable=false)
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    
    @Column(name="nombre_permiso", nullable=false, length=30)
    public String getNombrePermiso() {
        return this.nombrePermiso;
    }
    
    public void setNombrePermiso(String nombrePermiso) {
        this.nombrePermiso = nombrePermiso;
    }




}


