package com.sc77.entities;
// Generated 27/04/2017 05:32:16 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plazo generated by hbm2java
 */
@Entity
@Table(name="Plazo"
    ,catalog="sc77la_dev"
)
public class Plazo  implements java.io.Serializable {


     private Integer idPlazo;
     private CatalogoPlazo catalogoPlazo;
     private Date fechaInico;
     private Date fechaFin;
     private Set examens = new HashSet(0);

    public Plazo() {
    }

	
    public Plazo(CatalogoPlazo catalogoPlazo, Date fechaInico, Date fechaFin) {
        this.catalogoPlazo = catalogoPlazo;
        this.fechaInico = fechaInico;
        this.fechaFin = fechaFin;
    }
    public Plazo(CatalogoPlazo catalogoPlazo, Date fechaInico, Date fechaFin, Set examens) {
       this.catalogoPlazo = catalogoPlazo;
       this.fechaInico = fechaInico;
       this.fechaFin = fechaFin;
       this.examens = examens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_plazo", unique=true, nullable=false)
    public Integer getIdPlazo() {
        return this.idPlazo;
    }
    
    public void setIdPlazo(Integer idPlazo) {
        this.idPlazo = idPlazo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_catalogo_plazo", nullable=false)
    public CatalogoPlazo getCatalogoPlazo() {
        return this.catalogoPlazo;
    }
    
    public void setCatalogoPlazo(CatalogoPlazo catalogoPlazo) {
        this.catalogoPlazo = catalogoPlazo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inico", nullable=false, length=10)
    public Date getFechaInico() {
        return this.fechaInico;
    }
    
    public void setFechaInico(Date fechaInico) {
        this.fechaInico = fechaInico;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="plazo")
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


