package com.sc77.entities;
// Generated 27/04/2017 05:32:16 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Programa generated by hbm2java
 */
@Entity
@Table(name="Programa"
    ,catalog="sc77la_dev"
)
public class Programa  implements java.io.Serializable {


     private Integer idPrograma;
     private Parte parte;
     private Date horaInicio;
     private Date horaFin;
     private Set examens = new HashSet(0);

    public Programa() {
    }

	
    public Programa(Parte parte, Date horaInicio, Date horaFin) {
        this.parte = parte;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
    }
    public Programa(Parte parte, Date horaInicio, Date horaFin, Set examens) {
       this.parte = parte;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.examens = examens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_programa", unique=true, nullable=false)
    public Integer getIdPrograma() {
        return this.idPrograma;
    }
    
    public void setIdPrograma(Integer idPrograma) {
        this.idPrograma = idPrograma;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_parte", nullable=false)
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="hora_inicio", nullable=false, length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="hora_fin", nullable=false, length=8)
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="programa")
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


