package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Programa generated by hbm2java
 */
@Entity
@Table(name="Programa"
    ,catalog="sc77la_dev"
)
public class Programa  implements java.io.Serializable {


     private Integer idPrograma;
     private Examen examen;
     private Parte parte;
     private Date horaInicio;
     private Date horaFin;

    public Programa() {
    }

    public Programa(Examen examen, Parte parte, Date horaInicio, Date horaFin) {
       this.examen = examen;
       this.parte = parte;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_programa", unique=true, nullable=false)
    public Integer getIdPrograma() {
        return this.idPrograma;
    }
    
    public void setIdPrograma(Integer idPrograma) {
        this.idPrograma = idPrograma;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_examen", nullable=false)
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_parte", nullable=false)
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="hora_inicio", nullable=false, length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="hora_fin", nullable=false, length=8)
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }




}


