package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="Provincia"
    ,catalog="sc77la_dev"
)
public class Provincia  implements java.io.Serializable {


     private Integer idProvincia;
     private Autonomia autonomia;
     private String nombreProvincia;
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(Autonomia autonomia, String nombreProvincia) {
        this.autonomia = autonomia;
        this.nombreProvincia = nombreProvincia;
    }
    public Provincia(Autonomia autonomia, String nombreProvincia, Set localidads) {
       this.autonomia = autonomia;
       this.nombreProvincia = nombreProvincia;
       this.localidads = localidads;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_provincia", unique=true, nullable=false)
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_autonomia", nullable=false)
    public Autonomia getAutonomia() {
        return this.autonomia;
    }
    
    public void setAutonomia(Autonomia autonomia) {
        this.autonomia = autonomia;
    }
    
    @Column(name="nombre_provincia", nullable=false, length=80)
    public String getNombreProvincia() {
        return this.nombreProvincia;
    }
    
    public void setNombreProvincia(String nombreProvincia) {
        this.nombreProvincia = nombreProvincia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="provincia")
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


