package com.sc77.entities;
// Generated 01/05/2017 09:52:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="Usuario"
    ,catalog="sc77la_dev"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Perfil perfil;
     private String usernameUsuario;
     private String passwordUsuario;
     private Set contactos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Perfil perfil, String usernameUsuario, String passwordUsuario) {
        this.perfil = perfil;
        this.usernameUsuario = usernameUsuario;
        this.passwordUsuario = passwordUsuario;
    }
    public Usuario(Perfil perfil, String usernameUsuario, String passwordUsuario, Set contactos) {
       this.perfil = perfil;
       this.usernameUsuario = usernameUsuario;
       this.passwordUsuario = passwordUsuario;
       this.contactos = contactos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_perfil", nullable=false)
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    
    @Column(name="username_usuario", nullable=false, length=35)
    public String getUsernameUsuario() {
        return this.usernameUsuario;
    }
    
    public void setUsernameUsuario(String usernameUsuario) {
        this.usernameUsuario = usernameUsuario;
    }
    
    @Column(name="password_usuario", nullable=false, length=80)
    public String getPasswordUsuario() {
        return this.passwordUsuario;
    }
    
    public void setPasswordUsuario(String passwordUsuario) {
        this.passwordUsuario = passwordUsuario;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set contactos) {
        this.contactos = contactos;
    }




}


